resources:
  - name: build-protobuf
    type: git
    source:
      uri: https://github.com/blinksh/build-protobuf
      branch: master
      private_key: {{private-repo-key}}

  - name: protobuf-release
    type: github-release
    source:
      user: blinksh
      access_token: {{currents-gh-access-token}}
      repository: build-protobuf
      release: false
      pre-release: true

  - name: build-libssh2
    type: git
    source:
      uri: https://github.com/blinksh/libssh2-for-iOS
      branch: master
      private_key: {{private-repo-key}}

  - name: libssh2-release
    type: github-release
    source:
      user: blinksh
      access_token: {{currents-gh-access-token}}
      repository: libssh2-for-iOS
      release: false
      pre-release: true

  - name: openssl-release
    type: github-release
    source:
      user: blinksh
      access_token: {{currents-gh-access-token}}
      repository: OpenSSL-for-iPhone
      release: false
      pre-release: true

  - name: build-mosh
    type: git
    source:
      uri: https://github.com/blinksh/build-mosh
      branch: master
      private_key: {{private-repo-key}}

  - name: libmoshios-release
    type: github-release
    source:
      user: blinksh
      access_token: {{currents-gh-access-token}}
      repository: build-mosh
      release: false
      pre-release: true

  - name: blink
    type: git
    source:
      uri: git@github.com:carloscabanero/blink
      branch: ci
      private_key: {{private-repo-key}}
  - name: ci
    type: git
    source:
      uri: git@github.com:carloscabanero/blinkci
      branch: master
      private_key: {{private-repo-key}}

jobs:
  - name: build-protobuf-libs
    plan:
    - get: build-protobuf
    - get: ci
    - task: build
      config:
        platform: darwin
        run:
          path: ./ci/build-protobuf.sh
        inputs:
          - name: build-protobuf
          - name: ci
        outputs:
          - name: release
    - put: protobuf-release
      params:
        name: release/VERSION
        tag: release/VERSION
        globs:
          - release/protobuf-*.tar.gz

  - name: build-libmoshios
    plan:
    - get: build-mosh
    - get: ci
    - task: build
      config:
        platform: darwin
        run:
          path: ./ci/build-libmoshios.sh
        inputs:
          - name: build-mosh
          - name: ci
        outputs:
          - name: release
    - put: libmoshios-release
      params:
        name: release/VERSION
        tag: release/VERSION
        globs:
          - release/libmoshios-*.framework.tar.gz

  - name: build-libssh2
    plan:
    - get: build-libssh2
    - get: ci
    - task: build
      config:
        platform: darwin
        run:
          path: ./ci/build-libssh2.sh
        inputs:
          - name: build-libssh2
          - name: ci
        outputs:
          - name: release
    - put: libssh2-release
      params:
        name: release/LIBSSH2_VER
        tag: release/LIBSSH2_VER
        globs:
          - release/libssh2-*.framework.tar.gz
    - put: openssl-release
      params:
        name: release/OPENSSL_VER
        tag: release/OPENSSL_VER
        globs:
          - release/openssl-*.framework.tar.gz


  - name: build-blink
    plan:
      - get: blink
      - get: ci
      - task: build
        config:
          platform: darwin
          run:
            path: ./ci/build-blink.sh
          inputs:
            - name: blink
            - name: ci
          outputs:
            - name: release
